# Generated by Django 4.2 on 2023-04-18 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Lastname',
            new_name='lastname',
        ),
    ]
